[package]
name = "mock"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eth-types = { path = "../eth-types" }
external-tracer = { path = "../external-tracer" }
lazy_static.workspace = true
itertools.workspace = true
ethers-signers = "2.0.7"
ethers-core = { version = "2.0.7", features = ["scroll"] }
rand_chacha = "0.3"
rand = "0.8"
log.workspace = true

[features]
default = []
shanghai = ["eth-types/shanghai"]
scroll = ["eth-types/scroll", "external-tracer/scroll"]
