[package]
name = "bus-mapping"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eth-types = { path = "../eth-types" }
gadgets = { path = "../gadgets" }
keccak256 = { path = "../keccak256" }
mpt-zktrie = {path = "../zktrie"}
mock = { path = "../mock", optional = true }

ethers-core = { version = "2.0.7", features = ["scroll"] }
ethers-signers = "2.0.7"
ethers-providers = "2.0.7"
halo2_proofs.workspace = true
poseidon-circuit = { git = "https://github.com/scroll-tech/poseidon-circuit.git", branch = "scroll-dev-0901"}
itertools.workspace = true
lazy_static.workspace = true
log.workspace = true
num = "0.4"
rand = { version = "0.8", optional = true }
serde = {version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"
strum = "0.24"
hex = "0.4.3"
strum_macros = "0.24"

# precompile related crates
revm-precompile = { git = "https://github.com/scroll-tech/revm", branch = "scroll-fix" }
once_cell = "1.17.0"

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "1.0.0"
tokio = { version = "1.13", features = ["macros"] }
url = "2.2.2"
ctor = "0.1.22"
env_logger.workspace = true
mock = { path = "../mock" }
rand = "0.8"

[features]
default = ["test"]
test = ["mock", "rand"]
scroll = ["eth-types/scroll", "mock?/scroll"]
# Enable shanghai feature of mock only if mock is enabled (by test).
shanghai = ["eth-types/shanghai", "mock?/shanghai"]
