[package]
name = "bus-mapping"
version = "0.1.0"
edition = "2021"
authors = ["CPerezz <c.perezbaro@gmail.com>"]

[dependencies]
eth-types = { path = "../eth-types" }
ethers-core = "0.6"
ethers-providers = "0.6"
itertools = "0.10"
lazy_static = "1.4"
log = "0.4.14"
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256" }
serde = {version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"

[dev-dependencies]
mock = { path = "../mock" }
pretty_assertions = "1.0.0"
tokio = { version = "1.13", features = ["macros"] }
url = "2.2.2"
