[package]
name = "zkevm-circuits"
version = "0.1.0"
authors = ["therealyingtong <yingtong@z.cash>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.10"
halo2 = "0.0"
pasta_curves = "0.1"
bigint = "4"
num = "0.4"
sha3 = "0.7.2"
digest = "0.7.6"
array-init = "2.0.0"
paste = "1.0"
bus-mapping = { path = "../bus-mapping"}
hex = "0.4.3"

[dev-dependencies]
criterion = "0.3"
num = "0.4"

[[bench]]
name = "binary_value"
harness = false
