[package]
name = "zkevm-circuits"
version = "0.1.0"
authors = ["therealyingtong <yingtong@z.cash>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.11"
halo2_proofs = { git = "https://github.com/scroll-tech/halo2.git", rev = "a49778f5" }
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256" }
bigint = "4"
num = "0.4"
sha3 = "0.7.2"
digest = "0.7.6"
array-init = "2.0.0"
paste = "1.0"
bus-mapping = { path = "../bus-mapping" }
eth-types = { path = "../eth-types" }
gadgets = { path = "../gadgets" }
ethers-core = "0.6"
serde_json = "1.0.66"
strum = "0.24"
strum_macros = "0.24"
rand_xorshift = "0.3"
rand = "0.8"
itertools = "0.10.3"
lazy_static = "1.4"
keccak256 = { path = "../keccak256"}
log = "0.4.14"
env_logger = "0.9"

[dev-dependencies]
criterion = "0.3"
ctor = "0.1.22"
env_logger = "0.9.0"
hex = "0.4.3"
mock = { path = "../mock" }
itertools = "0.10.1"

[[bench]]
name = "binary_value"
harness = false

[features]
default = []
test = []
