[target.'cfg(target_os="macos")']
rustflags = ["-C", "link-args=-framework CoreFoundation -framework Security -framework CoreServices"]
[net]
git-fetch-with-cli = true
[env]
RUST_MIN_STACK = "16777216"
