name: Integration Tests

on:
  pull_request:
    types: [synchronize, labeled]
    # Ignore when target branch is `main` and source branch is scroll-stable.
    # It could avoid running twice. Since scroll-stable is set as `push` below.
    branches-ignore:
      - main
  push:
    branches:
      - scroll-stable

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  consecutiveness:
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'trigger-integration-tests')

    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/consecutive-workflow-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  wakeuprunner:
    if: github.event.pull_request.draft == false

    needs: [consecutiveness]
    name: Wake up self-hosted runner
    runs-on: pse-runner

    steps:
      - uses: actions/checkout@v2
      - run: |
          .github/integrationTestsScripts/wakeUpRunner.sh

  integration-tests:
    if: github.event.pull_request.draft == false

    needs: [wakeuprunner]
    name: Integration Tests
    runs-on: integration-tests-runner

    defaults:
      run:
        working-directory: ./integration-tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.18
      # https://github.com/actions/cache/issues/133#issuecomment-599102035
      - name: Change cached dir owner
        run: sudo rm -rf ~/go/pkg/mod/* &>/dev/null
      # Go cache for building geth-utils
      - name: Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
        # https://github.com/actions/cache/issues/810
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SECRET_REPO_DEPLOY_KEY }}
      # Run an initial build in a separate step to split the build time from execution time
      - name: Build bins
        run: cargo build --bin gen_blockchain_data
      - name: Build tests
        run: for testname in rpc circuit_input_builder circuits; do cargo test --profile release --test $testname --features $testname --no-run; done
      - run: ./run.sh --steps "setup"
      - run: ./run.sh --steps "gendata"
      - run: ./run.sh --steps "tests" --tests "rpc"
      - run: ./run.sh --steps "tests" --tests "circuit_input_builder"
      - run: RUST_TEST_THREADS=1 ./run.sh --steps "tests" --tests "circuits::mock_prover"
      - run: ./run.sh --steps "cleanup"
